[package]
name = "foopack-core"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
config = { noarch = true }                              # pure Python only; drop this if you add native code

[package.host-dependencies]
hatchling = ">=1.27,<2.0"
uv = "*"

[package.run-dependencies]
numpy = ">=1.26,<3"
xarray = ">=2024.6,<2026"
