[project]
name = "foopack-core"
version = "0.1.4"
description = "Core utilities for Foopack"
requires-python = ">=3.10"
dependencies = ["numpy>=1.26", "xarray>=2024.6.0"]

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::coverage.exceptions.CoverageWarning",
]

[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing"]

[tool.coverage.report]
skip_empty = true
exclude_also = [
    "pragma: no cover",
]

[tool.coverage.paths]
source = [
    "src/",
    "*/site-packages/",
]
