[package]
name = "foopack-extras"
version = "0.1.4"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
config = { noarch = true }

[package.host-dependencies]
hatchling = ">=1.27,<2.0"
uv = "*"

[package.run-dependencies]
foopack-core = "==0.1.4"
pandas = ">=2.2,<3"
