[project]
name = "foopack-extras"
version = "0.1.4"
description = "Extras for Foopack (depends on core)"
requires-python = ">=3.10"
dependencies = ["foopack-core==0.1.4", "pandas>=2.2"]

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::coverage.exceptions.CoverageWarning",
]

[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing"]

[tool.coverage.report]
skip_empty = true
exclude_also = [
    "pragma: no cover",
]

[tool.coverage.paths]
source = [
    "src/",
    "*/site-packages/",
]
