[package]
name = "foopack-ui"
version = "0.1.6"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
config = { noarch = true }

[package.host-dependencies]
hatchling = ">=1.27,<2.0"
uv = "*"

[package.run-dependencies]
foopack-core = "==0.1.6"
panel = ">=1.4,<2"
bokeh = ">=3.5,<4"
