name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  qa:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.54.2
          cache: true
      - run: pixi run qa-core
      - run: pixi run qa-extras
      - run: pixi run qa-ui
