name: Publish downstream app image (GHCR)
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["app/**"]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-22.04
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/foopack-app:latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.IMAGE }}
            ghcr.io/${{ github.repository_owner }}/foopack-app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
