name: Release (prefix.dev)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    env:
      OUTDIR: \${{ github.workspace }}/output
      PREFIX_CHANNEL: \${{ secrets.PREFIX_CHANNEL || 'foopack' }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.54.2
          cache: true
          log-level: vv
      - run: pixi build -vv --output-dir "\${OUTDIR}" -p packages/core
      - run: pixi build -vv --output-dir "\${OUTDIR}" -p packages/extras
      - run: pixi build -vv --output-dir "\${OUTDIR}" -p packages/ui
      - name: Upload to prefix.dev
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PREFIX_CHANNEL: \${{ env.PREFIX_CHANNEL }}
        run: |
          for f in \${OUTDIR}/*.conda; do
            echo "Uploading \$f"
            rattler-build upload prefix --channel "\$PREFIX_CHANNEL" "\$f"
          done
