name: Release (prefix.dev)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    env:
      OUTDIR: \${{ github.workspace }}/output
      PREFIX_CHANNEL: \${{ secrets.PREFIX_CHANNEL || 'foopack' }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.54.2
          cache: true
          log-level: vv
      - name: Install rattler-build
        run: pixi global install rattler-build
      - name: Build foopack-core
        working-directory: packages/core
        run: pixi build -vv --output-dir "\$GITHUB_WORKSPACE/output"
      - name: Build foopack-extras
        working-directory: packages/extras
        run: pixi build -vv --output-dir "\$GITHUB_WORKSPACE/output"
      - name: Build foopack-ui
        working-directory: packages/ui
        run: pixi build -vv --output-dir "\$GITHUB_WORKSPACE/output"
      - name: Upload to prefix.dev
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PREFIX_CHANNEL: \${{ secrets.PREFIX_CHANNEL || 'foopack' }}
        run: |
          shopt -s globstar || true
          for f in "$GITHUB_WORKSPACE"/output/**/*.conda; do
            echo "Uploading $f"
            rattler-build upload prefix --channel "$PREFIX_CHANNEL" "$f"
          done
