[project]
name = "foopack-runtime"
version = "0.1.0"
description = "Runtime container demonstrating foopack package installation"
channels = [
    "https://repo.prefix.dev/foopack",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = ">=3.12.0,<3.14"
# Install all foopack packages from prefix.dev
foopack-core = "*"
foopack-extras = "*"
foopack-ui = "*"

[tasks]
demo = "python -c 'import foopack_core, foopack_extras, foopack_ui; print(foopack_core.hello()); print(foopack_extras.hello_extras()); print(foopack_ui.hello_ui())'"
